default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rubymobile
  password: rbpassword

development:
  <<: *default
  database: evote_development

test:
  <<: *default
  database: evote_test

production:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host:     <%= ENV['DATABASE_HOST'] %>